import os
import sys
import psycopg2

def drop_tables(cursor, connection):
    '''
    Function to drop all tables in the NHL database to prepare for
    reinsertion.
    Inputs:
    connection - Connection to the PostgreSQL database

    Outputs:
    None
    '''
    # get list of tables in the NHL database
    cursor.execute("select relname from pg_class where relkind='r' and relname !~ '^(pg_|sql_)';")
    tables = cursor.fetchall()
    tables = [table[0] for table in tables]

    print(tables)

    for table in tables:
        test = 'DROP TABLE IF EXISTS nhl_tables.{};'.format(table)
        cursor.execute(test)
        connection.commit()

def create_tables(cursor, connection):
    '''
    Function to create all the tables needed for the NHL SQL database

    Inputs:
    connection - Connection to the PostgreSQL database

    Outputs:
    None
    '''

#create schedule table of the results of every nhl game
    cursor.execute("""
                   CREATE TABLE nhl_tables.nhl_schedule(
                   game_id integer primary key,
                   game_type text,
                   season text,
                   game_date date,
                   home_team_id integer,
                   home_team text,
                   home_score integer,
                   away_team_id integer,
                   away_team text,
                   away_score integer)
                """
                  )

#create table to store all nhl teams
    cursor.execute("""
                   CREATE TABLE nhl_tables.nhl_teams(
                   team_id integer primary key,
                   name text,
                   abbrev text,
                   division text,
                   conference text,
                   active text)
                   """)

#create table to store all nhl players past and present
    cursor.execute("""
                   CREATE TABLE nhl_tables.nhl_players(
                   id integer primary key,
                   name text,
                   birth_date date,
                   nationality text,
                   height text,
                   weight integer,
                   active text,
                   shoot_catches text,
                   position text)
                   """)

#Create Table to store raw pbp
    cursor.execute("""
                   CREATE TABLE nhl_tables.master_pbp(
                   game_id integer,
                   date date,
                   period integer,
                   event text,
                   description text,
                   time_elapsed text,
                   seconds_elapsed integer,
                   strength text,
                   ev_zone text,
                   type text,
                   ev_team text,
                   home_zone text,
                   away_team text,
                   home_team text,
                   p1_name text,
                   p1_id integer,
                   p2_name text,
                   p2_id integer,
                   p3_name text,
                   p3_id integer,
                   awayplayer1 text,
                   awayplayer1_id integer,
                   awayplayer2 text,
                   awayplayer2_id integer,
                   awayplayer3 text,
                   awayplayer3_id integer,
                   awayplayer4 text,
                   awayplayer4_id integer,
                   awayplayer5 text,
                   awayplayer5_id integer,
                   awayplayer6 text,
                   awayplayer6_id integer,
                   homeplayer1 text,
                   homeplayer1_id integer,
                   homeplayer2 text,
                   homeplayer2_id integer,
                   homeplayer3 text,
                   homeplayer3_id integer,
                   homeplayer4 text,
                   homeplayer4_id integer,
                   homeplayer5 text,
                   homeplayer5_id integer,
                   homeplayer6 text,
                   homeplayer6_id integer,
                   away_players integer,
                   home_players integer,
                   away_score integer,
                   home_score integer,
                   away_goalie text,
                   away_goalie_id integer,
                   home_goalie text,
                   home_goalie_id integer,
                   xc int,
                   yc int,
                   home_coach text,
                   away_coach text,
                   priority integer,
                   time_diff float,
                   event_length float,
                   is_corsi integer,
                   is_fenwick integer,
                   is_shot integer,
                   is_goal integer,
                   season integer,
                   score_diff integer,
                   is_home integer,
                   is_penalty integer,
                   is_hit integer,
                   prior_x_coords float,
                   prior_y_coords float,
                   dist_to_prior float,
                   distance float,
                   angle float,
                   is_rebound integer,
                   rebound_angle float,
                   is_rush float,
                   shooter_strength float,
                   xg float,
                   adj_corsi float,
                   adj_fenwick float,
                   adj_xg float)
                   """)

    cursor.execute("""
                   CREATE TABLE nhl_tables.player_allsits(
                   season integer,
                   game_id integer,
                   date date,
                   team text,
                   player_id int,
                   player_name text,
                   toi float,
                   CF integer,
                   CA integer,
                   FF integer,
                   FA integer,
                   SF integer,
                   SA integer,
                   GF integer,
                   GA integer,
                   xga float,
                   xgf float,
                   pent integer,
           pend integer,
                   iCF integer,
                   iFF integer,
                   iSF integer,
                   ixg float,
                   g integer,
                   a1 integer,
                   a2 integer,
                   iPENT integer,
                   iPEND integer,
                   iHF integer,
                   iHA integer,
                   iGA integer,
                   iTA integer,
                   FOW integer,
                   FOL integer,
                   BLK integer)
                   """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_allsits_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)
    cursor.execute("""
               CREATE TABLE nhl_tables.player_5v5(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_5v5_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_4v4(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_4v4_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_3v3(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_3v3_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_5v3(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_5v3_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_3v5(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_3v5_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_3v4(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_3v4_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_4v3(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_4v3_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_5v4(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_5v4_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_4v5(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF integer,
               CA integer,
               FF integer,
               FA integer,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF integer,
               iFF integer,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

    cursor.execute("""
               CREATE TABLE nhl_tables.player_4v5_adj(
               season integer,
               game_id integer,
               date date,
               team text,
               player_id int,
               player_name text,
               toi float,
               CF float,
               CA float,
               FF float,
               FA float,
               SF integer,
               SA integer,
               GF integer,
               GA integer,
               xga float,
               xgf float,
               pent integer,
           pend integer,
               iCF float,
               iFF float,
               iSF integer,
               ixg float,
               g integer,
               a1 integer,
               a2 integer,
               iPENT integer,
               iPEND integer,
               iHF integer,
               iHA integer,
               iGA integer,
               iTA integer,
               FOW integer,
               FOL integer,
               BLK integer)
               """)

#TODO create tables to store team stats
def main():

    '''
    Function to drop all tables in the existing database and create new ones
    for insertion of stats to setup the database fresh
    Inputs:
    None

    Outputs:
    None
    '''
    conn = psycopg2.connect(os.environ.get('DEV_DB_CONNECT'))
    cur = conn.cursor()

    drop_tables(cur, conn)
    create_tables(cur, conn)
    conn.commit()


if __name__ == '__main__':
    main()
